"use client";
import React, { FC, useState, useEffect } from "react";
import SearchBar from "@/components/payment_management/searchbar";
import Navbar from "@/components/common/navbar";
import axios from "axios";
import Link from "next/link";
import html2pdf from 'html2pdf.js';

interface Payment {
  id: string;
  paymentId: string;
  name: string;
  paymentType: string;
  paymentDate: Date;
  updateDate: Date;
  completed: boolean;
}

const Payment: FC = () => {
  const [filteredPayments, setFilteredPayments] = useState<Payment[]>([]);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [formData, setFormData] = useState<Payment>({
    id: "",
    paymentId: "",
    name: "",
    paymentType: "",
    paymentDate: new Date(),
    updateDate: new Date(),
    completed: false,
  });

  useEffect(() => {
    axios
      .get<Payment[]>("http://localhost:8080/payment")
      .then((response) => {
        console.log(response);
        setFilteredPayments(response.data);
        setPayments(response.data);
      })
      .catch((error) => {
        console.error("Error fetching payments:", error);
      });
  }, []);

  const editPayment = (paymentId: string) => {
    const payment = payments.find((p) => p.id === paymentId);
    if (payment) {
      setFormData(payment);
    }
  };

  const deletePayment = async (paymentId: string) => {
    try {
      await axios.delete(`http://localhost:8080/payment/${paymentId}`);
      alert("Payment deleted successfully");
      setPayments(payments.filter((p) => p.id !== paymentId));
    } catch (error) {
      console.error("Error deleting payment:", error);
      alert("Failed to delete payment");
    }
  };

  const handleSearch = (query: string) => {
    const lowerCaseQuery = query.toLowerCase();
    const filter = payments.filter((payment) => 
      payment.paymentId.toLowerCase().includes(lowerCaseQuery) ||
      payment.paymentType.toLowerCase().includes(lowerCaseQuery)
    );
    setFilteredPayments(filter);
  };

  const updatePayment = async () => {
    try {
      await axios.put(
        `http://localhost:8080/payment/${formData.id}`,
        formData
      );
      alert("Payment updated successfully");
      // Update state with the updated payment data
      setPayments((prevPayments) =>
        prevPayments.map((p) => (p.id === formData.id ? formData : p))
      );
    } catch (error) {
      console.error("Error updating payment:", error);
      alert("Failed to update payment");
    }
  };


  
  const generatePDF = () => {
    // Get current date and time
    const now = new Date();
    const formattedDateTime = now.toLocaleString();

    const header = `
        <h1 class="text-xl font-semi-bold mt-8 text-center text-gray-500">KpopShop Nexus</h1>
      `;
    const content = document.createElement('div');
    content.innerHTML =
      `<head>
    <!-- Load Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="flex flex-col items-center justify-center h-full">
      ${header}<header class="mb-8 text-sm text-gray-500 text-center">
        No: 87, Kandy Road, Kiribathgoda, Sri Lanka. </br> 076 366 3881 </br> <hr class="mt-4 w-9/10 mx-auto border-t border-gray-400">
          </header>
      <table >
        <thead class="bg-gray-800 text-white rounded-t-lg">
          <tr >
            <th class="px-4 py-2 pb-5">Id</th>
            <th class="px-4 py-2 pb-5">Name</th>
            <th class="px-4 py-2 pb-5">Payment Type</th>
            <th class="px-4 py-2 pb-5">Payment Date</th>
            <th class="px-4 py-2 pb-5">Update Date</th>
          </tr>
        </thead>
        <tbody>
          ${filteredPayments.map((payment)=> `
            <tr class="px-4 py-2">
              <td class="px-4 py-2 pb-2">${payment.paymentId}</td>
              <td class="px-4 py-2 pb-2">${payment.name}</td>
              <td class="px-4 py-2 pb-2">${payment.paymentType}</td>
              <td class="px-4 py-2 pb-2">${new Date(payment.paymentDate).getFullYear()}/${new Date(payment.paymentDate).getMonth() + 1}/${new Date(payment.paymentDate).getDate()}</td>
              <td class="px-4 py-2 pb-2">${new Date(payment.updateDate).getFullYear()}/${(new Date(payment.updateDate).getMonth() + 1).toString().padStart(2, '0')}/${new Date(payment.updateDate).getDate().toString().padStart(2, '0')}
</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      </div>
        
      <footer class="mt-8 mb-4 text-sm text-gray-500 text-center">
          <hr class="w-full mx-auto border-t border-gray-400">Generated by Review Management </br>${formattedDateTime}</br>
          </footer>
     
    </body>
    </html>
    `;

    html2pdf()
      .from(content)
      .save();
  };


  return (
    <div>
      <Navbar />
      <div className="mt-[90px] ml-[320px]">
        <div>
          <SearchBar title="Search " onSearch={handleSearch} />
          <br />
          <br />
          <div className="flex flex-row items-start justify-start gap-[2.125rem] max-w-full mq750:flex-wrap">
            <button className="cursor-pointer py-[0.687rem] px-[3.062rem] bg-darkmagenta rounded-6xl shadow-[0px_4px_4px_rgba(0,_0,_0,_0.25)] overflow-hidden flex flex-row items-center justify-center whitespace-nowrap border-[1px] border-solid border-darkmagenta rounded-[50px] hover:bg-mediumorchid hover:box-border hover:border-[1px] hover:border-solid hover:border-mediumorchid">
              <Link href="/payment_management/Payment/savePayment">
                <b className="relative text-[1rem] text-white text-left">
                  + Add Payment
                </b>
              </Link>
            </button>
          <button className="cursor-pointer py-[0.687rem] px-[3.062rem] bg-darkmagenta rounded-6xl shadow-[0px_4px_4px_rgba(0,_0,_0,_0.25)] overflow-hidden flex flex-row items-center justify-center whitespace-nowrap border-[1px] border-solid border-darkmagenta rounded-[50px] hover:bg-mediumorchid hover:box-border hover:border-[1px] hover:border-solid hover:border-mediumorchid"
           onClick={generatePDF}>
            <b className="relative text-[1rem] text-white text-left">
               Generate PDF Report
           </b>
        </button>
            
          </div>
        </div>

        <div className="flex flex-col gap-4 mt-[20px] mr-[20px]">
          <div className="max-h-[350px] overflow-y-auto">
            <table className="w-full table-auto">
              <thead>
                <tr className="h-12">
                  <th scope="col" className="sticky top-0 bg-fuchsia-800">
                    Payment ID
                  </th>
                  <th scope="col" className="sticky top-0 bg-fuchsia-800">
                    Customer Name
                  </th>
                  <th scope="col" className="sticky top-0 bg-fuchsia-800">
                    Payment Type
                  </th>
                  <th scope="col" className="sticky top-0 bg-fuchsia-800">
                    Payment Date and Time
                  </th>
                  <th scope="col" className="sticky top-0 bg-fuchsia-800">
                    Update Date and Time
                  </th>
                  <th scope="col" className="sticky top-0 bg-fuchsia-800">
                    Option
                  </th>
                </tr>
              </thead>

              <tbody>
                {filteredPayments.map((payment) => (
                  <tr key={payment.id} className="h-12 text-center bg-zinc-300 text-black">
                    <td>{payment.paymentId}</td>
                    <td>{payment.name}</td>
                    <td>{payment.paymentType}</td>
                    <td>{new Date(payment.paymentDate).toLocaleString()}</td>
                    <td>{new Date(payment.updateDate).toLocaleString()}</td>
                    <td>
                      <button
                        type="button"
                        className="btn btn-warning"
                        onClick={() => editPayment(payment.id)}
                      >
                        Edit
                      </button>
                      <button
                        type="button"
                        className="btn btn-danger"
                        onClick={() => deletePayment(payment.id)}
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Form for updating payment */}
            <table className="w-full table-auto">
              <tbody>
                <tr className="h-12 text-center bg-zinc-300 text-black">
                  <td>
                    <input
                      type="text"
                      className="w-20"
                      name="paymentId"
                      value={formData.paymentId}
                      onChange={(e) =>
                        setFormData({ ...formData, paymentId: e.target.value })
                      }
                      placeholder="0001"
                    />
                  </td>
                  <td>
                    <input
                      type="text"
                      name="name"
                      value={formData.name}
                      onChange={(e) =>
                        setFormData({ ...formData, name: e.target.value })
                      }
                      placeholder="Lakshan W V D"
                    />
                  </td>
                  <td>
                    <input
                      type="text"
                      name="paymentType"
                      className="w-20"
                      value={formData.paymentType}
                      onChange={(e) =>
                        setFormData({ ...formData, paymentType: e.target.value })
                      }
                      placeholder="COD/Bank"
                    />
                  </td>
                  <td>
                    <input type="text" name="paymentDate" value={new Date(formData.paymentDate).toLocaleString()} readOnly />
                  </td>
                  <td>
                    <input type="text" name="updateDate" value={new Date(formData.updateDate).toLocaleString()} readOnly />
                  </td>
                  <td>
                    <button type="button" className="btn btn-warning" onClick={updatePayment}>
                      Update
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Payment;
