import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Importing the Inter font from Google Fonts
import "./globals.css"; // Importing global styles

// Initialize the Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Define metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the Inter font class to the body */}
      <body className={inter.className}>
        {/* Render the children components */}
        {children}
      </body>
    </html>
  );
}
