
export const metadata: Metadata = {
  title: "KpopShop",

  description: "Generated by kpopShop",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        </body>
    </html>
  );
}
